### ISSUE TITLE
Repeats last utterance when starting up

### ISSUE THREAD

**Issue by krisgesling** [LinusS1/fallback-recommendations-skill#9]
Hey Linus,

We had an issue logged in mycroft-core that got traced back to this Skill so I thought you be interested to see it:
https://github.com/MycroftAI/mycroft-core/issues/2155

I haven't dug into it at all, but have you seen this behaviour before?

**Comment by LinusSkucas** [comment]
Thanks @krisgesling for the heads up! I haven't seen of this issue but I'll take a look at it.

@trekjunky if you could answer these questions (and cope with more on the way) that would be great to help me debug the skill:

1. What was the utterance that you said that was repeated?
2. Did Mycroft say the utterance that you exactly said, or did Mycroft say the answer to your request?
3. Before you turned mycroft off, did it ask if you wanted to install a skill?


4. Finally, Can you upload the log files you sent to Mycroft (the company). This would help me debug even further.

Thanks,
Linus

**Comment by trekjunky** [comment]
1. Tell me about Coleman Young
2. I typed it because I don't have a microphone, so it was exactly as I typed
3. no, i have it installed on my Linux desktop and I use CTRL+C to exit Mycroft, then in the command line, I usually stop the services still running in the background with (without the quotes) "cd ~/mycroft-core/" then "./stop-mycroft.sh" and it stops ALL services and skills
4. I had several problems and uploaded several logs. I am assuming you want the one that Ake used to diagnose the issue in the subject. I still have the zip file in my directory. I will attach it to this post.
[skills.tar.gz](https://github.com/LinusS1/fallback-recommendations-skill/files/3283821/skills.tar.gz)
BTW, Between Ake and Kris, we solved it. I first uninstalled recommendations. Then I tested and the problem went away, then I installed recommendations and tested again. Problem did NOT come back

**Comment by LinusSkucas** [comment]
Okay, how the fallback skill works is that after the skill is installed, on the users request, the skill "replays" the failed utterance for mycroft, and has that skill pick up on it.

It sounds like the fallback skill installed another skill but wasn't able to replay the utterance before you stopped mycroft. In this case, when you started mycroft up, its replayed that utterance.

**Comment by LinusSkucas** [comment]
Okay, I'm going to close this with the culprit being that the utterance had not been cleared due to a power cycle (or something like that)
